package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

import javafx.scene.control.ComboBox;

public class TiendaViewController implements Initializable {
	@FXML
	private TextField txtName;
	@FXML
	private TextField txtIdentification;
	@FXML
	private TextField txtCode;
	@FXML
	private TextArea txtAddress;
	@FXML
	private ComboBox<String> cmbClientType;
	@FXML
	private Button btnRegister;
	@FXML
	private Button btnCancel;

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		String[] listClientTypes = {"Inactivo", "Activo", "Frecuente"};
		ObservableList<String> items = FXCollections.observableArrayList(listClientTypes);
		cmbClientType.setItems(items);
		cmbClientType.setValue("Seleccione el tipo de cliente");

	}

	// Event Listener on Button[#btnRegister].onAction
	@FXML
	public void btnRegisterOnAction(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void btnCancelOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
